---
- name: Create pgdumper dir
  file:
    dest="{{pgdumper_dir}}"
    mode="0700"
    state=directory

- name: Create pgdumper dirs
  file:
    dest="{{pgdumper_dir}}/{{item}}"
    state=directory
  with_items:
    - dumps
    - cron.d
    - home

- name: Copy pgdumper crontab
  template:
    src: crontab
    dest: "{{pgdumper_dir}}/cron.d/crontab"
  notify: plan to restart

- name: Copy pgdumper script
  copy:
    src: pgdumper.py
    dest: "{{pgdumper_dir}}/home/pgdumper.py"
  notify: plan to restart

- name: Create .pgpass file
  template:
    src: pgpass
    dest: "{{pgdumper_dir}}/home/.pgpass"
    mode: "0600"
  notify: plan to restart

- meta: flush_handlers

- name: (Re)start pgdumper container
  docker_container:
    name: pgdumper
    image: "{{pgdumper_docker_image}}"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - "{{pgdumper_dir}}/cron.d:/etc/cron.d"
      - "{{pgdumper_dir}}/dumps:/dumps"
      - "{{pgdumper_dir}}/home:/var/backups"
    network_mode: host
    pull: "{{__pgdumper_restart | default(false)}}"
    restart: "{{__pgdumper_restart | default(false)}}"
    restart_policy: always
    state: started
